"""Rule JSON contract: schema, verbatim public quotes, SPEC-table exclusions, conformance.

The eight ``rules/json/<id>.json`` files are generated by ``scripts/sync_rule_text.py`` from
P2's committed public corpus. Tests that need the corpus skip (with the path) when it is not
checked out beside this repo (CI runs keyless and corpus-less).
"""

import importlib.util
import json
import os
import sys
from collections.abc import Iterator
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest
from pydantic import ValidationError

from caregap.measures.ids import (
    ALL_MEASURES,
    CONFORMANCE_NOTICE,
    MEASURE_NAMES,
    STAR_IDS,
    MeasureId,
)
from caregap.measures.rule_text import (
    RuleElement,
    RuleText,
    all_rule_texts,
    load_rule_text,
    rule_text_path,
)

REPO = Path(__file__).resolve().parents[3]
SCRIPT = REPO / "scripts" / "sync_rule_text.py"
DOCS = REPO / "docs" / "MEASURES.md"
CORPUS = Path(
    os.environ.get(
        "CAREGAP_P2_CORPUS",
        str(REPO.parent / "hedis-spec-copilot" / "corpus" / "committed" / "cms-tn-2026.json"),
    )
)

#: SPEC section 2 "Coded exclusions" column -> element slug -> expected (tag, coverage).
SPEC_EXCLUSIONS: dict[MeasureId, dict[str, tuple[str, str]]] = {
    "CBP": {
        "death": ("quoted", "observable"),
        "hospice": ("quoted", "observable"),
        "esrd": ("quoted", "observable"),
        "dialysis": ("demo_choice", "observable"),
        "pregnancy": ("quoted", "observable"),
        "kidney_transplant": ("demo_choice", "observable"),
    },
    "EED": {
        "death": ("quoted", "observable"),
        "hospice": ("quoted", "observable"),
    },
    "BCS": {
        "death": ("quoted", "observable"),
        "hospice": ("quoted", "observable"),
        "bilateral_mastectomy": ("not_representable", "not_representable"),
    },
    "COL": {
        "death": ("quoted", "observable"),
        "hospice": ("quoted", "observable"),
        "colorectal_cancer": ("quoted", "observable"),
        "total_colectomy": ("not_representable", "not_representable"),
    },
    "SPC": {
        "death": ("quoted", "observable"),
        "hospice": ("quoted", "observable"),
        "esrd_or_dialysis": ("quoted", "observable"),
        "pregnancy": ("quoted", "observable"),
        "cirrhosis": ("not_representable", "not_representable"),
        "myalgia_myositis_myopathy_rhabdomyolysis": ("not_representable", "not_representable"),
    },
    "SPD": {
        "death": ("demo_choice", "observable"),
        "hospice": ("quoted", "observable"),
        "esrd_or_dialysis": ("quoted", "observable"),
    },
    "TSC": {
        "death": ("demo_choice", "observable"),
        "hospice": ("demo_choice", "observable"),
    },
    "SNS": {
        "death": ("demo_choice", "observable"),
        "hospice": ("demo_choice", "observable"),
    },
}

#: SPEC section 2 "Escalations" column -> coverage-element slugs.
SPEC_ESCALATIONS: dict[MeasureId, set[str]] = {
    "CBP": {
        "e1_prior_hospice",
        "e4_advanced_illness_hint",
        "e5_incomplete_panel_or_unit",
        "e6_hypertension_abated_in_my",
    },
    "EED": {"e1_prior_hospice", "e4_advanced_illness_hint", "e6_diabetes_abated_in_my"},
    "BCS": {"e1_prior_hospice", "e4_advanced_illness_hint"},
    "COL": {"e1_prior_hospice", "e4_advanced_illness_hint", "e7_ambiguous_colon_code"},
    "SPC": {"e1_prior_hospice", "e4_advanced_illness_hint", "e3_medication_status_conflict"},
    "SPD": {"e1_prior_hospice", "e4_advanced_illness_hint", "e3_medication_status_conflict"},
    "TSC": {"e1_prior_hospice", "e4_advanced_illness_hint", "no_measure_escalations"},
    "SNS": {"e1_prior_hospice", "e4_advanced_illness_hint", "no_measure_escalations"},
}

TN_MEASURES: tuple[MeasureId, ...] = ("CBP", "EED", "BCS", "COL", "SPC", "SPD")
CITE_ONLY_MEASURES: tuple[MeasureId, ...] = ("TSC", "SNS")


def _raw(measure_id: MeasureId) -> dict[str, Any]:
    data: dict[str, Any] = json.loads(rule_text_path(measure_id).read_text(encoding="utf-8"))
    return data


@pytest.fixture(scope="module")
def corpus() -> dict[str, Any]:
    if not CORPUS.exists():
        pytest.skip(
            f"P2 corpus not checked out at {CORPUS} (set CAREGAP_P2_CORPUS); "
            "verbatim-quote and generator-drift checks need it"
        )
    data: dict[str, Any] = json.loads(CORPUS.read_text(encoding="utf-8"))
    return data


@pytest.fixture(scope="module")
def generator(corpus: dict[str, Any]) -> ModuleType:
    spec = importlib.util.spec_from_file_location("sync_rule_text", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # dataclasses resolve postponed annotations through sys.modules[cls.__module__].
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _sections(corpus: dict[str, Any], star_id: str, page: int | None) -> list[str]:
    for m in corpus["measures"]:
        if m["measure_id"] == star_id:
            return [str(s["text"]) for s in m["sections"] if page is None or s.get("page") == page]
    return []


def _citation(text: str) -> tuple[str, int | None]:
    doc_id, _, locator = text.partition(" ")
    page = int(locator[2:]) if locator.startswith("p.") else None
    return doc_id, page


def _quotes(text: RuleText) -> Iterator[tuple[str, str, str]]:
    """(label, citation, verbatim string) for everything that claims to be public wording."""
    for e in text.elements:
        if e.quote is not None:
            yield e.id, e.citation, e.quote
    if text.normative_quote is not None:
        yield "normative_quote.metric", text.normative_quote.citation, text.normative_quote.metric
        if text.normative_quote.description:
            yield (
                "normative_quote.description",
                text.normative_quote.citation,
                text.normative_quote.description,
            )
    if text.tn_sections:
        for key, section in text.tn_sections.items():
            yield f"tn_sections.{key}", f"cms-tn-2026 p.{section.page}", section.text


# --- schema -------------------------------------------------------------------------------


@pytest.mark.parametrize("measure_id", ALL_MEASURES)
def test_json_validates_against_model(measure_id: MeasureId) -> None:
    text = RuleText.model_validate(_raw(measure_id))
    assert text.measure_id == measure_id
    assert text.star_id == STAR_IDS[measure_id]
    assert text.name == MEASURE_NAMES[measure_id]
    assert text.rule_version == f"{measure_id.lower()}-v1"
    assert load_rule_text(measure_id) == text


@pytest.mark.parametrize("measure_id", ALL_MEASURES)
def test_conformance_string_exact(measure_id: MeasureId) -> None:
    assert _raw(measure_id)["conformance"] == "demo-grade; HEDIS-aligned; not NCQA-certified"
    assert load_rule_text(measure_id).conformance == CONFORMANCE_NOTICE


def test_all_rule_texts_covers_every_measure() -> None:
    assert tuple(all_rule_texts()) == ALL_MEASURES


@pytest.mark.parametrize("measure_id", ALL_MEASURES)
def test_every_kind_present_and_tags_well_formed(measure_id: MeasureId) -> None:
    text = load_rule_text(measure_id)
    kinds = {e.kind for e in text.elements}
    assert kinds == {"denominator", "numerator", "exclusion", "timeline", "coverage"}
    for e in text.elements:
        assert e.id.startswith(f"{measure_id.lower()}/{e.kind}/")
        if e.source == "quoted":
            assert e.quote == e.text
        else:
            assert e.rationale, f"{e.id}: demo/not_representable elements must say WHY"
        if e.kind == "exclusion":
            assert e.coverage in {"observable", "partial", "not_representable"}
    assert {e.coverage for e in text.elements_of("exclusion")} <= {
        "observable",
        "partial",
        "not_representable",
    }


@pytest.mark.parametrize("measure_id", TN_MEASURES)
def test_tn_measures_cite_the_public_domain_corpus(measure_id: MeasureId) -> None:
    text = load_rule_text(measure_id)
    tn = next(s for s in text.sources if s.doc_id == "cms-tn-2026")
    assert tn.license_posture == "us_gov_public_domain"
    assert tn.page is not None
    assert text.normative_quote is not None
    assert text.tn_sections is not None
    assert set(text.tn_sections) == {"description", "metric", "exclusions", "data_time_frame"}
    quoted = [e for e in text.elements if e.source == "quoted"]
    assert quoted, "a Technical Notes measure must quote its public wording"
    for e in quoted:
        doc_id, page = _citation(e.citation)
        assert doc_id == "cms-tn-2026" and page is not None, e.id


@pytest.mark.parametrize("measure_id", CITE_ONLY_MEASURES)
def test_screening_measures_quote_nothing(measure_id: MeasureId) -> None:
    text = load_rule_text(measure_id)
    assert text.star_id is None
    assert all(e.source != "quoted" and e.quote is None for e in text.elements)
    assert text.normative_quote is None and text.tn_sections is None
    postures = {s.license_posture for s in text.sources}
    assert "public_web_cite_only" in postures and "us_gov_public_domain" not in postures
    urls = {s.url for s in text.sources}
    expected = {
        "TSC": "https://ecqi.healthit.gov/ecqm/ep/2025/cms138v13",
        "SNS": "https://www.ncqa.org/hedis/measures/social-need-screening-and-intervention/",
    }[measure_id]
    assert expected in urls


# --- SPEC section 2 table ---------------------------------------------------------------


@pytest.mark.parametrize("measure_id", ALL_MEASURES)
def test_every_spec_table_exclusion_has_an_element(measure_id: MeasureId) -> None:
    text = load_rule_text(measure_id)
    by_slug = {e.id.rsplit("/", 1)[1]: e for e in text.elements_of("exclusion")}
    for slug, (tag, coverage) in SPEC_EXCLUSIONS[measure_id].items():
        assert slug in by_slug, f"{measure_id}: SPEC exclusion {slug!r} has no element"
        assert by_slug[slug].source == tag, f"{measure_id}/{slug}: tag"
        assert by_slug[slug].coverage == coverage, f"{measure_id}/{slug}: coverage"
    assert text.coverage_table.keys() == {e.id for e in text.elements_of("exclusion")}


@pytest.mark.parametrize("measure_id", ALL_MEASURES)
def test_every_spec_table_escalation_has_a_coverage_element(measure_id: MeasureId) -> None:
    slugs = {e.id.rsplit("/", 1)[1] for e in load_rule_text(measure_id).elements_of("coverage")}
    assert slugs == SPEC_ESCALATIONS[measure_id]


def test_spec_table_demo_choices_are_stated() -> None:
    texts = all_rule_texts()
    bcs = texts["BCS"].element("bcs/numerator/window_27_months")
    assert bcs.source == "demo_choice" and "Oct 1 of MY-2" in bcs.text
    cbp = texts["CBP"].element("cbp/denominator/hypertension_active")
    assert cbp.source == "demo_choice" and "Dec 31 of the MY" in cbp.text
    spc = texts["SPC"].element("spc/numerator/on_therapy_status")
    assert spc.source == "demo_choice" and "status == active" in spc.text
    spd = texts["SPD"].element("spd/denominator/diabetes_diagnosis_proxy")
    assert spd.source == "demo_choice" and spd.quote is not None
    for slug in ("dialysis", "kidney_transplant"):
        assert texts["CBP"].element(f"cbp/exclusion/{slug}").source == "demo_choice"
    assert texts["BCS"].normative_quote is not None
    assert texts["BCS"].normative_quote.conflict is not None


# --- verbatim against P2's corpus -----------------------------------------------------------


@pytest.mark.parametrize("measure_id", TN_MEASURES)
def test_quotes_are_verbatim_in_p2_corpus(corpus: dict[str, Any], measure_id: MeasureId) -> None:
    text = load_rule_text(measure_id)
    assert text.star_id is not None
    assert corpus["doc_id"] == "cms-tn-2026"
    tn = next(s for s in text.sources if s.doc_id == "cms-tn-2026")
    assert tn.url == corpus["source_url"]
    assert tn.retrieval_date.isoformat() == corpus["retrieval_date"]
    for label, citation, quote in _quotes(text):
        doc_id, page = _citation(citation)
        assert doc_id == "cms-tn-2026", f"{measure_id}/{label}: quote cites {doc_id}"
        sections = _sections(corpus, text.star_id, page)
        assert sections, f"{measure_id}/{label}: no corpus section on page {page}"
        assert any(quote in s for s in sections), (
            f"{measure_id}/{label}: not verbatim in {citation}: {quote!r}"
        )


def test_committed_json_and_docs_match_generator(
    corpus: dict[str, Any], generator: ModuleType
) -> None:
    built = generator.build_all(generator.load_corpus(CORPUS))
    for measure_id in ALL_MEASURES:
        assert built[measure_id].model_dump(mode="json") == _raw(measure_id), (
            f"{measure_id}: rules/json is stale -- run scripts/sync_rule_text.py"
        )
    rendered = str(generator.render_docs(built))
    assert DOCS.read_text(encoding="utf-8") == rendered, (
        "docs/MEASURES.md is stale -- run scripts/sync_rule_text.py --render-docs"
    )


# --- model guards -------------------------------------------------------------------------


def test_model_rejects_quoted_element_without_matching_quote() -> None:
    with pytest.raises(ValidationError, match="quote == text"):
        RuleElement(
            id="cbp/denominator/age",
            kind="denominator",
            text="18-85",
            source="quoted",
            citation="cms-tn-2026 p.56",
            quote="something else",
        )


def test_model_rejects_demo_choice_without_rationale() -> None:
    with pytest.raises(ValidationError, match="rationale"):
        RuleElement(
            id="cbp/numerator/x", kind="numerator", text="x", source="demo_choice", citation="c"
        )


def test_model_rejects_exclusion_without_coverage_and_bad_ids() -> None:
    with pytest.raises(ValidationError, match="coverage"):
        RuleElement(
            id="cbp/exclusion/x",
            kind="exclusion",
            text="x",
            source="demo_choice",
            citation="c",
            rationale="why",
        )
    with pytest.raises(ValidationError, match="does not match kind"):
        RuleElement(
            id="cbp/numerator/x",
            kind="exclusion",
            text="x",
            source="demo_choice",
            citation="c",
            rationale="why",
            coverage="observable",
        )


def test_model_rejects_wrong_conformance_and_unknown_source() -> None:
    raw = _raw("BCS")
    bad = {**raw, "conformance": "certified"}
    with pytest.raises(ValidationError, match="conformance"):
        RuleText.model_validate(bad)
    bad = {**raw, "sources": [s for s in raw["sources"] if s["doc_id"] != "ncqa-bcs"]}
    with pytest.raises(ValidationError, match="unknown source"):
        RuleText.model_validate(bad)
