"""Rule text: the tagged, citable statement of every demo-grade measure rule.

``rules/json/<id>.json`` is GENERATED by ``scripts/sync_rule_text.py`` from P2's committed
public-domain corpus (CMS 2026 Part C & D Star Ratings Technical Notes) plus cite-only public
URLs (NCQA / eCQI summaries, the public ACC/AHA statin-intensity table) and this repo's SPEC
(section 2). Never edit the JSON by hand; re-run the script.

Every element carries one tag (ADR-0005):

``quoted``
    ``text`` is a verbatim public sentence (``quote == text``); the citation names the corpus
    document and page the sentence was lifted from.
``demo_choice``
    a parameter this demo fixed (window, code set, status rule, proxy); ``rationale`` says WHY.
``not_representable``
    a public criterion Synthea / P6 cannot evidence; ``quote`` keeps the public wording so the
    coverage table can show exactly what is missing.

Element ``kind`` mirrors the SPEC section 2 table columns: ``denominator``, ``numerator``,
``exclusion`` (each with a ``coverage`` verdict), ``timeline`` (measurement-year mechanics), and
``coverage`` (escalation hints E1-E7: things the engine can only surface for a human).

The engine never reads these files. They feed the validator packet, the UI cards,
``/v1/measures``, and ``docs/MEASURES.md``.
"""

import json
import re
from datetime import date
from functools import cache
from importlib import resources
from importlib.resources.abc import Traversable
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from caregap.measures.ids import ALL_MEASURES, CONFORMANCE_NOTICE, MeasureId
from caregap.measures.models import Coverage

ElementKind = Literal["denominator", "numerator", "exclusion", "timeline", "coverage"]
ElementSource = Literal["quoted", "demo_choice", "not_representable"]
LicensePosture = Literal["us_gov_public_domain", "public_web_cite_only", "project_spec"]

_ELEMENT_ID = re.compile(r"^(?P<measure>[a-z]{3})/(?P<kind>[a-z]+)/(?P<slug>[a-z0-9_]+)$")


class RuleSource(BaseModel):
    """One citable source. ``page`` is the corpus page (PDF page index) for TN sources."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    doc_id: str
    title: str
    url: str
    page: int | None = None
    retrieval_date: date
    license_posture: LicensePosture
    note: str | None = None


class RuleElement(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    id: str
    """``<measure>/<kind>/<slug>``, e.g. ``cbp/denominator/age``."""
    kind: ElementKind
    text: str
    source: ElementSource
    citation: str
    """``<doc_id>`` optionally followed by a locator, e.g. ``cms-tn-2026 p.56``."""
    quote: str | None = None
    """Verbatim public wording. Required (and equal to ``text``) when ``source == quoted``."""
    rationale: str | None = None
    """WHY the demo fixed this parameter / cannot represent this criterion."""
    coverage: Coverage | None = None
    """Required for ``exclusion`` elements: observable | partial | not_representable."""

    @property
    def doc_id(self) -> str:
        return self.citation.split(" ", 1)[0]

    @model_validator(mode="after")
    def _check(self) -> "RuleElement":
        m = _ELEMENT_ID.match(self.id)
        if m is None:
            raise ValueError(f"element id {self.id!r} is not <measure>/<kind>/<slug>")
        if m.group("kind") != self.kind:
            raise ValueError(f"element id {self.id!r} does not match kind {self.kind!r}")
        if not self.text.strip():
            raise ValueError(f"element {self.id!r} has empty text")
        if self.source == "quoted":
            if self.quote is None or self.quote != self.text:
                raise ValueError(f"quoted element {self.id!r} must carry quote == text")
        elif self.rationale is None or not self.rationale.strip():
            raise ValueError(f"{self.source} element {self.id!r} needs a rationale")
        if self.kind == "exclusion" and self.coverage is None:
            raise ValueError(f"exclusion element {self.id!r} needs a coverage verdict")
        if self.source == "not_representable" and self.coverage == "observable":
            raise ValueError(f"not_representable element {self.id!r} cannot be observable")
        return self


class TnSection(BaseModel):
    """A verbatim Technical Notes section (public domain) carried for display."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    heading: str
    text: str
    page: int


class NormativeQuote(BaseModel):
    """The public one-sentence definition of the measure (Metric + Description)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    metric: str
    description: str | None = None
    citation: str
    conflict: str | None = None
    """Set when the public Description and Metric disagree (e.g. BCS 50-74 vs 52-74)."""


class RuleText(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    measure_id: MeasureId
    star_id: str | None
    name: str
    rule_version: str
    sources: list[RuleSource] = Field(min_length=1)
    elements: list[RuleElement] = Field(min_length=1)
    normative_quote: NormativeQuote | None = None
    tn_sections: dict[str, TnSection] | None = None
    conformance: str

    @model_validator(mode="after")
    def _check(self) -> "RuleText":
        if self.conformance != CONFORMANCE_NOTICE:
            raise ValueError(f"conformance must be exactly {CONFORMANCE_NOTICE!r}")
        doc_ids = [s.doc_id for s in self.sources]
        if len(set(doc_ids)) != len(doc_ids):
            raise ValueError("duplicate source doc_id")
        ids = [e.id for e in self.elements]
        if len(set(ids)) != len(ids):
            raise ValueError("duplicate element id")
        prefix = f"{self.measure_id.lower()}/"
        for e in self.elements:
            if not e.id.startswith(prefix):
                raise ValueError(f"element {e.id!r} does not belong to {self.measure_id}")
            if e.doc_id not in doc_ids:
                raise ValueError(f"element {e.id!r} cites unknown source {e.doc_id!r}")
        if (
            self.normative_quote is not None
            and self.normative_quote.citation.split(" ", 1)[0] not in doc_ids
        ):
            raise ValueError("normative_quote cites an unknown source")
        return self

    def elements_of(self, kind: ElementKind) -> list[RuleElement]:
        return [e for e in self.elements if e.kind == kind]

    def element(self, element_id: str) -> RuleElement:
        for e in self.elements:
            if e.id == element_id:
                return e
        raise KeyError(f"unknown element {element_id!r} in {self.measure_id}")

    @property
    def coverage_table(self) -> dict[str, Coverage]:
        """Every public exclusion criterion -> observable | partial | not_representable."""
        return {e.id: e.coverage for e in self.elements_of("exclusion") if e.coverage is not None}


#: Rule-module ``COVERAGE`` keys -> the rule JSON element id they cite. The rule modules
#: keep their own (public-criterion) vocabulary; this table is the join the UI / packet use.
#: ``tests/unit/measures/test_rule_json.py`` checks every key of every rule is mapped and
#: every target element exists.
COVERAGE_ELEMENTS: dict[MeasureId, dict[str, str]] = {
    "CBP": {
        "died_during_measurement_period": "cbp/exclusion/death",
        "hospice_during_measurement_period": "cbp/exclusion/hospice",
        "esrd": "cbp/exclusion/esrd",
        "dialysis": "cbp/exclusion/dialysis",
        "kidney_transplant": "cbp/exclusion/kidney_transplant",
        "pregnancy_during_measurement_period": "cbp/exclusion/pregnancy",
        "palliative_care": "cbp/exclusion/palliative_care",
        "frailty_and_advanced_illness_66_to_80": "cbp/exclusion/frailty_and_advanced_illness_66_80",
        "frailty_81_plus": "cbp/exclusion/frailty_81_plus",
        "institutional_snp_or_long_term_institution_66_plus": (
            "cbp/exclusion/isnp_or_long_term_institution_66_plus"
        ),
    },
    "EED": {
        "died_during_measurement_period": "eed/exclusion/death",
        "hospice_during_measurement_period": "eed/exclusion/hospice",
        "frailty_and_advanced_illness_66_plus": (
            "eed/exclusion/frailty_and_advanced_illness_66_plus"
        ),
        "palliative_care_during_measurement_period": "eed/exclusion/palliative_care",
        "institutional_snp_or_long_term_institution_66_plus": (
            "eed/exclusion/isnp_or_long_term_institution_66_plus"
        ),
        "gestational_or_steroid_induced_diabetes_without_diabetes_dx": (
            "eed/exclusion/no_diabetes_dx_with_pcos_gestational_or_steroid"
        ),
    },
    "BCS": {
        "died_during_measurement_period": "bcs/exclusion/death",
        "hospice_during_measurement_period": "bcs/exclusion/hospice",
        "bilateral_mastectomy": "bcs/exclusion/bilateral_mastectomy",
        "advanced_illness_and_frailty": "bcs/exclusion/frailty_and_advanced_illness_66_plus",
        "palliative_care": "bcs/exclusion/palliative_care",
    },
    "COL": {
        "numerator_colonoscopy_my_plus_9_prior_years": (
            "col/numerator/colonoscopy_my_plus_9_prior_years"
        ),
        "numerator_fobt_fit_in_my": "col/numerator/fobt_fit_in_my",
        "numerator_flexible_sigmoidoscopy_my_plus_4_prior_years": (
            "col/numerator/flexible_sigmoidoscopy_my_plus_4_prior_years"
        ),
        "numerator_ct_colonography_my_plus_4_prior_years": (
            "col/numerator/ct_colonography_my_plus_4_prior_years"
        ),
        "numerator_sdna_fit_my_plus_2_prior_years": "col/numerator/sdna_fit_my_plus_2_prior_years",
        "exclusion_death_during_measurement_period": "col/exclusion/death",
        "exclusion_hospice_during_measurement_period": "col/exclusion/hospice",
        "exclusion_colorectal_cancer_any_time": "col/exclusion/colorectal_cancer",
        "exclusion_total_colectomy_any_time": "col/exclusion/total_colectomy",
        "exclusion_palliative_care_during_measurement_period": "col/exclusion/palliative_care",
        "exclusion_isnp_or_long_term_institution_66_plus": (
            "col/exclusion/isnp_or_long_term_institution_66_plus"
        ),
        "exclusion_frailty_and_advanced_illness_66_plus": (
            "col/exclusion/frailty_and_advanced_illness_66_plus"
        ),
    },
    "SPC": {
        "died_during_measurement_period": "spc/exclusion/death",
        "hospice_during_measurement_period": "spc/exclusion/hospice",
        "esrd": "spc/exclusion/esrd_or_dialysis",
        "dialysis": "spc/exclusion/esrd_or_dialysis",
        "pregnancy": "spc/exclusion/pregnancy",
        "cirrhosis": "spc/exclusion/cirrhosis",
        "myalgia_myositis_myopathy_rhabdomyolysis": (
            "spc/exclusion/myalgia_myositis_myopathy_rhabdomyolysis"
        ),
        "in_vitro_fertilization": "spc/exclusion/in_vitro_fertilization",
        "clomiphene_dispensed": "spc/exclusion/clomiphene",
        "palliative_care": "spc/exclusion/palliative_care",
        "frailty_and_advanced_illness_66_plus": (
            "spc/exclusion/frailty_and_advanced_illness_66_plus"
        ),
        "institutional_snp_or_long_term_institution_66_plus": (
            "spc/exclusion/isnp_or_long_term_institution_66_plus"
        ),
    },
    "SPD": {
        "died_during_measurement_period": "spd/exclusion/death",
        "hospice_during_measurement_period": "spd/exclusion/hospice",
        "esrd": "spd/exclusion/esrd_or_dialysis",
        "dialysis": "spd/exclusion/esrd_or_dialysis",
        "pregnancy": "spd/exclusion/pregnancy",
        "in_vitro_fertilization": "spd/exclusion/pregnancy_lactation_and_fertility",
        "clomiphene_dispensed": "spd/exclusion/pregnancy_lactation_and_fertility",
        "cirrhosis": "spd/exclusion/cirrhosis",
        "myalgia_myositis_myopathy_rhabdomyolysis": "spd/exclusion/rhabdomyolysis_and_myopathy",
        "palliative_care": "spd/exclusion/palliative_care",
        "frailty_and_advanced_illness_66_plus": (
            "spd/exclusion/frailty_and_advanced_illness_66_plus"
        ),
        "institutional_snp_or_long_term_institution_66_plus": (
            "spd/exclusion/isnp_or_long_term_institution_66_plus"
        ),
        "diabetes_medication_only_with_pcos_gestational_or_steroid_induced": (
            "spd/exclusion/polycystic_ovary_syndrome"
        ),
    },
    "TSC": {
        "numerator_screening_in_my": "tsc/numerator/tobacco_status_answer",
        "numerator_tobacco_cessation_intervention": "tsc/numerator/cessation_intervention",
        "exclusion_death_during_measurement_period": "tsc/exclusion/death",
        "exclusion_hospice_during_measurement_period": "tsc/exclusion/hospice",
        "exclusion_palliative_care_during_measurement_period": "tsc/exclusion/palliative_care",
        "exclusion_isnp_or_long_term_institution_66_plus": (
            "tsc/exclusion/isnp_or_long_term_institution_66_plus"
        ),
        "exclusion_frailty_and_advanced_illness_66_plus": (
            "tsc/exclusion/frailty_and_advanced_illness_66_plus"
        ),
    },
    "SNS": {
        "numerator_screening_in_my": "sns/numerator/prapare_panel",
        "numerator_sdoh_intervention_food_housing_transportation_utility": (
            "sns/numerator/domain_screens_and_interventions"
        ),
        "numerator_domain_specific_sdoh_instruments": (
            "sns/numerator/domain_screens_and_interventions"
        ),
        "numerator_prapare_item_positivity_semantics": "sns/numerator/prapare_panel",
        "exclusion_death_during_measurement_period": "sns/exclusion/death",
        "exclusion_hospice_during_measurement_period": "sns/exclusion/hospice",
        "exclusion_palliative_care_during_measurement_period": "sns/exclusion/palliative_care",
        "exclusion_isnp_or_long_term_institution_66_plus": (
            "sns/exclusion/isnp_or_long_term_institution_66_plus"
        ),
        "exclusion_frailty_and_advanced_illness_66_plus": (
            "sns/exclusion/frailty_and_advanced_illness_66_plus"
        ),
    },
}


#: Exclusion elements that no rule ``COVERAGE`` key cites, each with the reason the join skips
#: it. The parity test requires every other exclusion element to be a ``COVERAGE_ELEMENTS``
#: target, so a new JSON exclusion row must be keyed by its rule or listed here.
UNKEYED_EXCLUSION_ELEMENTS: dict[str, str] = {
    "cbp/exclusion/pregnancy_status_observation": (
        "observation arm of the 'pregnancy_during_measurement_period' key (evidence.pregnancy_hits)"
    ),
    "spc/exclusion/pregnancy_status_observation": (
        "observation arm of the 'pregnancy' key (evidence.pregnancy_hits)"
    ),
    "spd/exclusion/pregnancy_status_observation": (
        "observation arm of the 'pregnancy' key (evidence.pregnancy_hits)"
    ),
    "spd/exclusion/prediabetes": "denominator trap, never an exclusion category",
    "bcs/exclusion/isnp_or_long_term_institution_66_plus": (
        "not_representable row carried by the JSON coverage table only; bcs.COVERAGE omits it"
    ),
}


def coverage_element_id(measure_id: MeasureId, coverage_key: str) -> str:
    """The rule JSON element a rule module's ``COVERAGE`` key cites (KeyError when unmapped)."""
    return COVERAGE_ELEMENTS[measure_id][coverage_key]


def rule_text_dir() -> Traversable:
    return resources.files("caregap.measures.rules") / "json"


def rule_text_path(measure_id: MeasureId) -> Traversable:
    return rule_text_dir() / f"{measure_id.lower()}.json"


@cache
def load_rule_text(measure_id: MeasureId) -> RuleText:
    raw = json.loads(rule_text_path(measure_id).read_text(encoding="utf-8"))
    text = RuleText.model_validate(raw)
    if text.measure_id != measure_id:
        raise ValueError(f"{measure_id.lower()}.json declares measure_id {text.measure_id!r}")
    return text


def all_rule_texts() -> dict[MeasureId, RuleText]:
    return {m: load_rule_text(m) for m in ALL_MEASURES}
